spring.application.name=demo
# Configuración de PostgreSQL (Render)
spring.datasource.url=jdbc:postgresql://db:5432/productos_db
spring.datasource.username=user_demo
spring.datasource.password=pass_demo
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

# SSL obligatorio para Render
#spring.datasource.hikari.data-source-properties.sslmode=require